# Generated by Django 4.2.9 on 2024-07-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.ImageField(blank=True, upload_to='profiles/')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Position', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Direction', models.CharField(blank=True, max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Phonenumber', models.IntegerField()),
                ('Facebook', models.URLField(blank=True)),
                ('Linkedin', models.URLField(blank=True)),
                ('Skype', models.CharField(blank=True, max_length=100)),
                ('Language', models.CharField(max_length=100)),
                ('Emailsignature', models.TextField(blank=True)),
                ('Departments', models.CharField(max_length=100)),
                ('Administrator', models.BooleanField(default=False)),
                ('SWE', models.BooleanField(default=False)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
