# Generated by Django 4.2.9 on 2024-07-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0002_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
