# Generated by Django 4.2.9 on 2024-07-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0003_alter_staff_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newproduct1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Productname', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
    ]
