# Generated by Django 4.2.9 on 2024-07-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0004_newproduct1'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDoctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Clinicname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Specialization', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Callstatus', models.CharField(max_length=50)),
            ],
        ),
    ]
