# Generated by Django 4.2.9 on 2024-07-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0005_newdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newdoctor',
            name='Phone',
            field=models.CharField(max_length=15),
        ),
    ]
