# Generated by Django 4.2.9 on 2024-07-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0006_alter_newdoctor_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status2', models.CharField(max_length=50)),
                ('Specialisation2', models.CharField(max_length=100)),
                ('Assigned2', models.CharField(max_length=50)),
                ('Tags2', models.CharField(max_length=50)),
                ('Name2', models.CharField(max_length=50)),
                ('Address2', models.CharField(max_length=100)),
                ('Position2', models.CharField(max_length=50)),
                ('City2', models.CharField(max_length=50)),
                ('Email2', models.EmailField(max_length=254, unique=True)),
                ('State2', models.CharField(max_length=50)),
                ('Website2', models.URLField(blank=True)),
                ('Company2', models.CharField(max_length=50)),
                ('Phone2', models.CharField(max_length=15)),
                ('Country2', models.CharField(max_length=50)),
                ('Zipcode2', models.CharField(max_length=50)),
                ('Language2', models.CharField(max_length=50)),
                ('Description2', models.TextField(max_length=200)),
                ('Public2', models.BooleanField(default=False)),
                ('ContactedToday2', models.BooleanField(default=False)),
                ('Priority2', models.CharField(max_length=50)),
                ('Remark2', models.TextField(max_length=200)),
            ],
        ),
    ]
