# Generated by Django 4.2.9 on 2024-07-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0008_newcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='newcustomer',
            name='Productname3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productname_customers', to='crmapp.newproduct1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newcustomer',
            name='Type3',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_customers', to='crmapp.newproduct1'),
            preserve_default=False,
        ),
    ]
