# Generated by Django 4.2.9 on 2024-07-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0009_newcustomer_productname3_newcustomer_type3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcustomer',
            old_name='Productname3',
            new_name='Productname',
        ),
        migrations.RenameField(
            model_name='newcustomer',
            old_name='Type3',
            new_name='Type',
        ),
    ]
