# Generated by Django 4.2.9 on 2024-07-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0010_rename_productname3_newcustomer_productname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newcustomer',
            name='Productname',
        ),
        migrations.RemoveField(
            model_name='newcustomer',
            name='Type',
        ),
    ]
