# Generated by Django 4.2.9 on 2024-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapp', '0011_remove_newcustomer_productname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=100)),
                ('cc', models.CharField(max_length=100)),
                ('assign', models.CharField(max_length=100)),
                ('priority', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('ipr', models.CharField(max_length=100)),
                ('ikbl', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('attach', models.FileField(upload_to='')),
            ],
        ),
    ]
